M48
; DRILL file {KiCad 7.0.2} date Fri May 24 23:14:02 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-24T23:14:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X127.5Y-66.642
X127.5Y-110.142
X170.0Y-66.642
X170.0Y-110.142
T2
X121.05Y-82.63
X121.05Y-94.06
T0
M30
